//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApi.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTraining
    {
        public int TrainingId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string TrainingDetails { get; set; }
        public string Effectiveness { get; set; }
        public int JobType { get; set; }
        public int EmployeeId { get; set; }
    }
}
